name: Format file

on:
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Prettier
        run: |
          npm ci
          npx --yes prettier --write src/app/features/config/productivity-tips.const.ts
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add src/app/features/config/productivity-tips.const.ts
          git commit -m "Format productivity-tips.const.ts with Prettier" || echo "No changes"
          git push
